In [1]:
import pandas as pd

# Read only the last sheet from the Excel file
excel_path = "Raw/scian_2023_categorias_y_productos.xlsx"
last_sheet_name = pd.ExcelFile(excel_path).sheet_names[-1]
df_last_sheet = pd.read_excel(excel_path, sheet_name=last_sheet_name)

In [2]:
df_last_sheet

,"Sistema de Clasificación Industrial de América del Norte, México SCIAN 2023",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,Código,Título,Descripción,Incluye,Excluye,Índice de bienes y servicios comprendidos en l...
1,111110,Cultivo de soya,Unidades económicas dedicadas principalmente a...,NaN,NaN,"frijoles de soya (grano) orgánicos, cultivo"
2,NaN,NaN,NaN,NaN,NaN,"frijoles de soya (grano), cultivo"
3,NaN,NaN,NaN,NaN,NaN,"soya (grano), cultivo"
4,NaN,NaN,NaN,NaN,NaN,"soya bragg (grano), cultivo"
...,...,...,...,...,...,...
36845,NaN,NaN,NaN,NaN,NaN,NaN
36846,932120,Sedes diplomáticas y otras unidades extraterri...,Unidades económicas extranjeras con ubicación ...,NaN,Excluye: unidades económicas gubernamentales d...,consulados con ubicación física en nuestro paí...
36847,NaN,NaN,NaN,NaN,NaN,embajadas con ubicación física en nuestro país...
36848,NaN,NaN,NaN,NaN,NaN,sedes diplomáticas y otras unidades extraterri...
36849,NaN,NaN,NaN,NaN,NaN,unidades militares que brindan apoyo en nuestr...

In [5]:
df_last_sheet = df_last_sheet[df_last_sheet.iloc[:, 0].notna()]

In [6]:
df_last_sheet

,"Sistema de Clasificación Industrial de América del Norte, México SCIAN 2023",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,Código,Título,Descripción,Incluye,Excluye,Índice de bienes y servicios comprendidos en l...
1,111110,Cultivo de soya,Unidades económicas dedicadas principalmente a...,NaN,NaN,"frijoles de soya (grano) orgánicos, cultivo"
23,111121,Cultivo de cártamo,Unidades económicas dedicadas principalmente a...,NaN,NaN,"cártamo (semilla), cultivo"
33,111122,Cultivo de girasol,Unidades económicas dedicadas principalmente a...,NaN,NaN,"flores de sol (semilla), cultivo"
41,111129,Cultivo anual de otras semillas oleaginosas,Unidades económicas dedicadas principalmente a...,Incluye también: u. e. d. p. al cultivo de sem...,Excluye: u. e. d. p. al cultivo de soya (11111...,"ajonjolí anual (semilla), cultivo"
...,...,...,...,...,...,...
35702,931610,Actividades administrativas de instituciones d...,Unidades económicas gubernamentales dedicadas ...,NaN,Excluye: u. e. d. p. a la administración de la...,actividades administrativas de instituciones e...
35744,931710,Relaciones exteriores,Unidades económicas gubernamentales dedicadas ...,NaN,"Excluye: embajadas, consulados y otras sedes d...",administración de relaciones exteriores
35748,931810,Actividades de seguridad nacional,Unidades económicas gubernamentales dedicadas ...,NaN,"Excluye: cuerpos de seguridad pública (931412,...","ejército, servicios del"
35753,932110,Organismos internacionales,Unidades económicas internacionales con repres...,NaN,NaN,Centro de Estudios Monetarios Latinoamericanos...
35761,932120,Sedes diplomáticas y otras unidades extraterri...,Unidades económicas extranjeras con ubicación ...,NaN,Excluye: unidades económicas gubernamentales d...,consulados con ubicación física en nuestro paí...

In [8]:
df_last_sheet = df_last_sheet.loc[1:].reset_index(drop=True)

In [13]:
df_last_sheet.rename(columns={'Sistema de Clasificación Industrial de América del Norte, México SCIAN 2023': 'Codigo', 'Unnamed: 1': 'Descripcion'}, inplace=True)
df_last_sheet = df_last_sheet[['Codigo', 'Descripcion']]
df_last_sheet

C:\Users\Edu\AppData\Local\Temp\ipykernel_8716\49062130.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_last_sheet.rename(columns={'Sistema de Clasificación Industrial de América del Norte, México SCIAN 2023': 'Codigo', 'Unnamed: 1': 'Descripcion'}, inplace=True)

      Codigo                                        Descripcion
0     111110                                   Cultivo de soya
1     111121                                Cultivo de cártamo
2     111122                                Cultivo de girasol
3     111129       Cultivo anual de otras semillas oleaginosas
4     111131                           Cultivo de frijol grano
...      ...                                                ...
1081  931610  Actividades administrativas de instituciones d...
1082  931710                             Relaciones exteriores
1083  931810                 Actividades de seguridad nacional
1084  932110                        Organismos internacionales
1085  932120  Sedes diplomáticas y otras unidades extraterri...

[1086 rows x 2 columns]

In [14]:
from unidecode import unidecode
import json

df_last_sheet['Descripcion'] = df_last_sheet['Descripcion'].apply(lambda x: unidecode(str(x)).lower())
codigo_descripcion_dict = dict(zip(df_last_sheet['Codigo'], df_last_sheet['Descripcion']))

json_str = json.dumps(codigo_descripcion_dict, ensure_ascii=False, indent=2)
print(json_str)

{
  "111110": "cultivo de soya ",
  "111121": "cultivo de cartamo ",
  "111122": "cultivo de girasol ",
  "111129": "cultivo anual de otras semillas oleaginosas ",
  "111131": "cultivo de frijol grano ",
  "111132": "cultivo de garbanzo grano ",
  "111139": "cultivo de otras leguminosas ",
  "111140": "cultivo de trigo ",
  "111151": "cultivo de maiz grano ",
  "111152": "cultivo de maiz forrajero ",
  "111160": "cultivo de arroz ",
  "111191": "cultivo de sorgo grano ",
  "111192": "cultivo de avena grano ",
  "111193": "cultivo de cebada grano ",
  "111194": "cultivo de sorgo forrajero ",
  "111195": "cultivo de avena forrajera ",
  "111199": "cultivo de otros cereales ",
  "111211": "cultivo de jitomate o tomate rojo ",
  "111212": "cultivo de chile ",
  "111213": "cultivo de cebolla ",
  "111214": "cultivo de melon ",
  "111215": "cultivo de tomate verde ",
  "111216": "cultivo de papa ",
  "111217": "cultivo de calabaza ",
  "111218": "cultivo de sandia ",
  "111219": "cultivo de otras hortalizas ",
  "111310": "cultivo de naranja ",
  "111321": "cultivo de limon ",
  "111329": "cultivo de otros citricos ",
  "111331": "cultivo de cafe ",
  "111332": "cultivo de platano ",
  "111333": "cultivo de mango ",
  "111334": "cultivo de aguacate ",
  "111335": "cultivo de uva ",
  "111336": "cultivo de manzana ",
  "111337": "cultivo de cacao ",
  "111338": "cultivo de coco ",
  "111339": "cultivo de otros frutales no citricos y de nueces ",
  "111411": "cultivo de jitomate en invernaderos y otras estructuras agricolas protegidas ",
  "111412": "cultivo de fresa en invernaderos y otras estructuras agricolas protegidas ",
  "111413": "cultivo de bayas (berries) en invernaderos y otras estructuras agricolas protegidas, excepto fresas ",
  "111414": "cultivo de chile en invernaderos y otras estructuras agricolas protegidas ",
  "111415": "cultivo de manzana en invernaderos y otras estructuras agricolas protegidas ",
  "111416": "cultivo de pepino en invernaderos y otras estructuras agricolas protegidas ",
  "111419": "cultivo de otros productos alimenticios en invernaderos y otras estructuras agricolas protegidas ",
  "111421": "floricultura a cielo abierto ",
  "111422": "floricultura en invernaderos y otras estructuras agricolas protegidas ",
  "111423": "cultivo de arboles de ciclo productivo de 10 anos o menos ",
  "111429": "otros cultivos no alimenticios en invernaderos y otras estructuras agricolas protegidas ",
  "111910": "cultivo de tabaco ",
  "111920": "cultivo de algodon ",
  "111930": "cultivo de cana de azucar ",
  "111941": "cultivo de alfalfa ",
  "111942": "cultivo de pastos ",
  "111991": "cultivo de agaves alcoholeros ",
  "111992": "cultivo de cacahuate ",
  "111993": "actividades agricolas combinadas con explotacion de animales ",
  "111994": "actividades agricolas combinadas con aprovechamiento forestal ",
  "111995": "actividades agricolas combinadas con explotacion de animales y aprovechamiento forestal ",
  "111999": "otros cultivos ",
  "112110": "explotacion de bovinos para la produccion de carne ",
  "112120": "explotacion de bovinos para la produccion de leche ",
  "112131": "explotacion de bovinos para la produccion conjunta de leche y carne ",
  "112139": "explotacion de bovinos para otros propositos ",
  "112211": "explotacion de porcinos en granja ",
  "112212": "explotacion de porcinos en traspatio ",
  "112311": "explotacion de gallinas para la produccion de huevo fertil ",
  "112312": "explotacion de gallinas para la produccion de huevo para plato ",
  "112320": "explotacion de pollos para la produccion de carne ",
  "112330": "explotacion de guajolotes o pavos ",
  "112340": "produccion de aves en incubadora ",
  "112390": "explotacion de otras aves para produccion de carne y huevo ",
  "112410": "explotacion de ovinos ",
  "112420": "explotacion de caprinos ",
  "112513": "camaronicultura y acuicultura de otros crustaceos en agua salada",
  "112514": "camaronicultura y acuicultura de otros crustaceos en agua dulce",
  "112515": "piscicultura en agua dulce",
  "112516": "piscicultura en agua salada",
  "112519": "otra acuicultura",
  "112910": "apicultura ",
  "112920": "explotacion de equidos ",
  "112930": "cunicultura y explotacion de animales con pelaje fino ",
  "112991": "explotacion de animales combinada con aprovechamiento forestal ",
  "112999": "explotacion de otros animales ",
  "113110": "silvicultura ",
  "113211": "viveros forestales ",
  "113212": "recoleccion de productos forestales ",
  "113310": "aprovechamiento de arboles",
  "114111": "pesca de camaron ",
  "114112": "pesca de tunidos ",
  "114113": "pesca de sardina y anchoveta ",
  "114119": "pesca y captura de otros peces, crustaceos, moluscos y otras especies ",
  "114210": "caza y captura ",
  "115111": "servicios de fumigacion agricola ",
  "115112": "despepite de algodon ",
  "115113": "beneficio de productos agricolas ",
  "115119": "otros servicios relacionados con la agricultura ",
  "115210": "servicios relacionados con la cria y explotacion de animales ",
  "115310": "servicios relacionados con el aprovechamiento forestal ",
  "211111": "extraccion de petroleo y gas natural asociado ",
  "211112": "extraccion de gas natural no asociado ",
  "212110": "mineria de carbon mineral ",
  "212210": "mineria de hierro ",
  "212221": "mineria de oro ",
  "212222": "mineria de plata ",
  "212231": "mineria de cobre ",
  "212232": "mineria de plomo y zinc ",
  "212291": "mineria de manganeso ",
  "212292": "mineria de mercurio y antimonio ",
  "212293": "mineria de uranio y minerales radiactivos ",
  "212299": "mineria de otros minerales metalicos ",
  "212311": "mineria de piedra caliza ",
  "212312": "mineria de marmol ",
  "212319": "mineria de otras piedras dimensionadas ",
  "212321": "mineria de arena y grava para la construccion ",
  "212322": "mineria de tezontle y tepetate ",
  "212323": "mineria de feldespato ",
  "212324": "mineria de silice ",
  "212325": "mineria de caolin ",
  "212329": "mineria de otras arcillas y de otros minerales refractarios ",
  "212391": "mineria de sal ",
  "212392": "mineria de piedra de yeso ",
  "212393": "mineria de barita ",
  "212394": "mineria de roca fosforica ",
  "212395": "mineria de fluorita ",
  "212396": "mineria de grafito ",
  "212397": "mineria de azufre ",
  "212398": "mineria de minerales no metalicos para productos quimicos ",
  "212399": "mineria de otros minerales no metalicos ",
  "213111": "perforacion de pozos petroleros y de gas ",
  "213119": "otros servicios relacionados con la mineria ",
  "221111": "generacion de electricidad a partir de combustibles fosiles ",
  "221112": "generacion de electricidad a partir de energia hidraulica ",
  "221113": "generacion de electricidad a partir de energia solar ",
  "221114": "generacion de electricidad a partir de energia eolica ",
  "221119": "generacion de electricidad a partir de otro tipo de energia ",
  "221121": "transmision de energia electrica ",
  "221122": "distribucion de energia electrica ",
  "221123": "comercializacion de energia electrica ",
  "221210": "suministro de gas natural por ductos al consumidor final ",
  "221311": "captacion, tratamiento y suministro de agua realizados por el sector privado ",
  "221312": "captacion, tratamiento y suministro de agua realizados por el sector publico ",
  "236111": "edificacion de vivienda unifamiliar ",
  "236112": "edificacion de vivienda multifamiliar ",
  "236113": "supervision de edificacion residencial ",
  "236211": "edificacion de naves y plantas industriales, excepto la supervision ",
  "236212": "supervision de edificacion de naves y plantas industriales ",
  "236221": "edificacion de inmuebles comerciales y de servicios, y otras edificaciones no residenciales, excepto la supervision",
  "236222": "supervision de edificacion de inmuebles comerciales y de servicios, y otras edificaciones no residenciales",
  "237111": "construccion de obras para el tratamiento, distribucion y suministro de agua y drenaje ",
  "237112": "construccion de sistemas de riego agricola ",
  "237113": "supervision de construccion de obras para el tratamiento, distribucion y suministro de agua, drenaje y riego ",
  "237121": "construccion de sistemas de distribucion de petroleo y gas ",
  "237122": "construccion de plantas de refineria y petroquimica ",
  "237123": "supervision de construccion de obras para petroleo y gas ",
  "237131": "construccion de obras de generacion y conduccion de energia electrica ",
  "237132": "construccion de obras para telecomunicaciones ",
  "237133": "supervision de construccion de obras de generacion y conduccion de energia electrica y de obras para telecomunicaciones ",
  "237211": "division de terrenos ",
  "237212": "construccion de obras de urbanizacion ",
  "237213": "supervision de division de terrenos y de construccion de obras de urbanizacion ",
  "237311": "instalacion de senalamientos y protecciones en obras viales ",
  "237312": "construccion de carreteras, puentes y similares ",
  "237313": "supervision de construccion de vias de comunicacion ",
  "237991": "construccion de presas y represas ",
  "237992": "construccion de obras maritimas, fluviales y subacuaticas ",
  "237993": "construccion de obras para transporte electrico y ferroviario ",
  "237994": "supervision de construccion de otras obras de ingenieria civil ",
  "237999": "otras construcciones de ingenieria civil ",
  "238110": "trabajos de cimentaciones ",
  "238121": "montaje de estructuras de concreto prefabricadas ",
  "238122": "montaje de estructuras de acero prefabricadas ",
  "238130": "trabajos de albanileria ",
  "238190": "otros trabajos en exteriores ",
  "238210": "instalaciones electricas en construcciones ",
  "238221": "instalaciones hidrosanitarias y de gas ",
  "238222": "instalaciones de sistemas centrales de aire acondicionado y calefaccion ",
  "238290": "otras instalaciones y equipamiento en construcciones ",
  "238311": "colocacion de muros falsos y aislamiento ",
  "238312": "trabajos de enyesado, empastado y tiroleado ",
  "238320": "trabajos de pintura y otros cubrimientos de paredes ",
  "238330": "colocacion de pisos flexibles y de madera ",
  "238340": "colocacion de pisos ceramicos y azulejos ",
  "238350": "realizacion de trabajos de carpinteria en el lugar de la construccion ",
  "238390": "otros trabajos de acabados en edificaciones ",
  "238910": "preparacion de terrenos para la construccion ",
  "238990": "otros trabajos especializados para la construccion ",
  "311110": "elaboracion de alimentos balanceados para animales ",
  "311211": "beneficio del arroz ",
  "311212": "elaboracion de harina de trigo ",
  "311213": "elaboracion de harina de maiz ",
  "311214": "elaboracion de harina de otros productos agricolas ",
  "311215": "elaboracion de malta ",
  "311221": "elaboracion de feculas y otros almidones y sus derivados ",
  "311222": "elaboracion de aceites y grasas vegetales comestibles ",
  "311230": "elaboracion de cereales para el desayuno ",
  "311311": "elaboracion de azucar de cana ",
  "311319": "elaboracion de otros azucares ",
  "311340": "elaboracion de dulces, chicles y productos de confiteria que no sean de chocolate ",
  "311350": "elaboracion de chocolate y productos de chocolate ",
  "311411": "congelacion de frutas y verduras ",
  "311412": "congelacion de guisos y otros alimentos preparados ",
  "311421": "deshidratacion de frutas y verduras ",
  "311422": "conservacion de frutas y verduras por procesos distintos a la congelacion y la deshidratacion ",
  "311423": "conservacion de guisos y otros alimentos preparados por procesos distintos a la congelacion ",
  "311511": "elaboracion de leche liquida ",
  "311512": "elaboracion de leche en polvo, condensada y evaporada ",
  "311513": "elaboracion de derivados y fermentos lacteos ",
  "311520": "elaboracion de helados y paletas ",
  "311611": "matanza de ganado, aves y otros animales comestibles ",
  "311612": "corte y empacado de carne de ganado, aves y otros animales comestibles ",
  "311613": "elaboracion de embutidos y otras conservas de carne de ganado, aves y otros animales comestibles",
  "311614": "elaboracion de manteca y otras grasas animales comestibles ",
  "311710": "preparacion y envasado de pescados y mariscos ",
  "311811": "panificacion industrial ",
  "311812": "panificacion tradicional ",
  "311813": "elaboracion de tortillas de harina de trigo de forma tradicional ",
  "311820": "elaboracion de galletas y pastas para sopa ",
  "311830": "elaboracion de tortillas de maiz y molienda de nixtamal ",
  "311910": "elaboracion de botanas ",
  "311921": "beneficio del cafe ",
  "311922": "elaboracion de cafe tostado y molido destinado a unidades que lo comercializan",
  "311923": "elaboracion de cafe instantaneo ",
  "311924": "preparacion y envasado de te ",
  "311930": "elaboracion de concentrados, polvos, jarabes y esencias de sabor para bebidas ",
  "311940": "elaboracion de condimentos y aderezos ",
  "311991": "elaboracion de gelatinas y otros postres en polvo ",
  "311992": "elaboracion de levadura ",
  "311993": "elaboracion de alimentos frescos para consumo inmediato ",
  "311999": "elaboracion de otros alimentos procesados y envasados",
  "312111": "elaboracion de refrescos y otras bebidas no alcoholicas ",
  "312112": "purificacion y embotellado de agua ",
  "312113": "elaboracion de hielo ",
  "312120": "elaboracion de cerveza ",
  "312131": "elaboracion de bebidas alcoholicas a base de uva ",
  "312132": "elaboracion de pulque ",
  "312139": "elaboracion de sidra y otras bebidas fermentadas ",
  "312141": "elaboracion de ron y otras bebidas destiladas de cana ",
  "312143": "obtencion de alcohol etilico potable ",
  "312144": "elaboracion de tequila",
  "312145": "elaboracion de mezcal",
  "312149": "elaboracion de otras bebidas destiladas ",
  "312210": "beneficio del tabaco ",
  "312221": "elaboracion de cigarros ",
  "312222": "elaboracion de puros y otros productos de tabaco ",
  "313111": "preparacion e hilado de fibras duras naturales ",
  "313112": "preparacion e hilado de fibras blandas naturales ",
  "313113": "fabricacion de hilos para coser y bordar ",
  "313210": "fabricacion de telas anchas de tejido de trama ",
  "313220": "fabricacion de telas angostas de tejido de trama y pasamaneria ",
  "313230": "fabricacion de telas no tejidas (comprimidas) ",
  "313240": "fabricacion de telas de tejido de punto ",
  "313310": "acabado de productos textiles ",
  "313320": "fabricacion de telas recubiertas ",
  "314110": "fabricacion de alfombras y tapetes ",
  "314120": "confeccion de cortinas, blancos y similares ",
  "314911": "confeccion de costales ",
  "314912": "confeccion de productos de textiles recubiertos y de materiales sucedaneos ",
  "314991": "confeccion, bordado y deshilado de productos textiles ",
  "314992": "fabricacion de redes y otros productos de cordeleria ",
  "314993": "fabricacion de borras y estopas",
  "314999": "fabricacion de banderas y otros productos textiles no clasificados en otra parte ",
  "315121": "fabricacion de calcetines y medias de tejido de punto",
  "315122": "fabricacion de ropa interior de tejido de punto",
  "315123": "fabricacion de ropa exterior de tejido de punto",
  "315210": "confeccion de prendas de vestir de cuero, piel y materiales sucedaneos ",
  "315221": "confeccion en serie de ropa interior y de dormir ",
  "315222": "confeccion en serie de camisas ",
  "315223": "confeccion en serie de uniformes ",
  "315224": "confeccion en serie de disfraces y trajes tipicos ",
  "315225": "confeccion de prendas de vestir sobre medida ",
  "315229": "confeccion en serie de otra ropa exterior de materiales textiles ",
  "315991": "confeccion de sombreros y gorras ",
  "315999": "confeccion de otros accesorios y prendas de vestir no clasificados en otra parte ",
  "316110": "curtido y acabado de cuero y piel ",
  "316211": "fabricacion de calzado con corte de piel y cuero ",
  "316212": "fabricacion de calzado con corte de tela ",
  "316213": "fabricacion de calzado de plastico ",
  "316214": "fabricacion de calzado de hule ",
  "316219": "fabricacion de huaraches y calzado de otro tipo de materiales ",
  "316991": "fabricacion de bolsos de mano, maletas y similares ",
  "316999": "fabricacion de otros productos de cuero, piel y materiales sucedaneos ",
  "321111": "aserraderos integrados ",
  "321112": "aserrado de tablas y tablones ",
  "321113": "tratamiento de la madera y fabricacion de postes y durmientes ",
  "321210": "fabricacion de laminados y aglutinados de madera ",
  "321910": "fabricacion de productos de madera para la construccion ",
  "321920": "fabricacion de productos para embalaje y envases de madera ",
  "321991": "fabricacion de productos de materiales trenzables, excepto palma ",
  "321992": "fabricacion de articulos y utensilios de madera para el hogar ",
  "321993": "fabricacion de productos de madera de uso industrial ",
  "321999": "fabricacion de otros productos de madera ",
  "322110": "fabricacion de pulpa ",
  "322121": "fabricacion de papel en plantas integradas ",
  "322122": "fabricacion de papel a partir de pulpa ",
  "322131": "fabricacion de carton en plantas integradas ",
  "322132": "fabricacion de carton y cartoncillo a partir de pulpa ",
  "322210": "fabricacion de envases de carton ",
  "322220": "fabricacion de bolsas de papel y productos celulosicos recubiertos y tratados ",
  "322230": "fabricacion de productos de papeleria ",
  "322291": "fabricacion de panales desechables y productos sanitarios ",
  "322299": "fabricacion de otros productos de carton y papel ",
  "323111": "impresion de libros, periodicos y revistas ",
  "323119": "impresion de formas continuas y otros impresos ",
  "323120": "industrias conexas a la impresion ",
  "324110": "refinacion de petroleo ",
  "324120": "fabricacion de productos de asfalto ",
  "324191": "fabricacion de aceites y grasas lubricantes ",
  "324199": "fabricacion de coque y otros productos derivados del petroleo refinado y del carbon mineral ",
  "325110": "fabricacion de petroquimicos basicos del gas natural y del petroleo refinado ",
  "325120": "fabricacion de gases industriales ",
  "325130": "fabricacion de pigmentos y colorantes sinteticos ",
  "325180": "fabricacion de otros productos quimicos basicos inorganicos ",
  "325190": "fabricacion de otros productos quimicos basicos organicos ",
  "325211": "fabricacion de resinas sinteticas ",
  "325212": "fabricacion de hules sinteticos ",
  "325220": "fabricacion de fibras quimicas ",
  "325310": "fabricacion de fertilizantes y composta",
  "325320": "fabricacion de plaguicidas y otros agroquimicos, excepto fertilizantes y composta",
  "325411": "fabricacion de materias primas para la industria farmaceutica ",
  "325412": "fabricacion de preparaciones farmaceuticas ",
  "325510": "fabricacion de pinturas y recubrimientos ",
  "325520": "fabricacion de adhesivos ",
  "325610": "fabricacion de jabones, limpiadores y dentifricos ",
  "325620": "fabricacion de cosmeticos, perfumes y otras preparaciones de tocador ",
  "325910": "fabricacion de tintas para impresion ",
  "325920": "fabricacion de explosivos ",
  "325991": "fabricacion de cerillos ",
  "325992": "fabricacion de peliculas, placas y papel fotosensible para fotografia ",
  "325993": "fabricacion de resinas de plasticos reciclados ",
  "325999": "fabricacion de otros productos quimicos ",
  "326110": "fabricacion de bolsas y peliculas de plastico",
  "326120": "fabricacion de tuberia y conexiones, y tubos para embalaje ",
  "326130": "fabricacion de laminados de plastico ",
  "326140": "fabricacion de espumas y productos de poliestireno ",
  "326150": "fabricacion de espumas y productos de uretano ",
  "326160": "fabricacion de botellas de plastico ",
  "326191": "fabricacion de productos de plastico para el hogar con y sin reforzamiento ",

In [15]:
with open(f"{last_sheet_name}.json", "w", encoding="utf-8") as f:
    f.write(json_str)